In [1]:
import pandas as pd
import plotly.graph_objects as go

from pathlib import Path
from pandas import DataFrame

In [2]:
def get_path(prev_folders: int = 0) -> str:
    """
    Identifies a specific directory according to the absolute path of the file.
    Args:
        prev_folders (int): An integer indicating the number of previous folders to get. If not given, 0 (current folder) is used by default.

    Returns:
        str: A text string with the identified path.
    """
    # Error handling
    if not isinstance(prev_folders, int) or prev_folders < 0:
        raise ValueError("prev_folders must be a non-negative integer")

    # Use pathlib to handle paths and directories
    path = Path.cwd()
    
    # Go up the specified number of directories
    for _ in range(prev_folders):
        path = path.parent
    
    # Use pathlib's as_posix method to get the string representation of the path
    # This automatically ensures the path ends with a slash
    path_str = path.as_posix() + '/'
    
    return path_str

In [3]:
def replace_value(df: DataFrame, column: str, old_value: str, new_value: str) -> DataFrame:
    """
    Replace a specific value in a DataFrame column with a new value.

    Args:
        df (DataFrame): The DataFrame containing the column to be modified.
        column (str): The name of the column to be modified.
        old_value (str): The value to be replaced.
        new_value (str): The new value to replace the old value.

    Returns:
        DataFrame: The modified DataFrame with the specified value replaced.
    """
    df[column] = df[column].str.replace(old_value, new_value, regex=False)
    return df

# Environment settings

In [4]:
pd.options.display.max_columns = None  # Remove "dots" from display when printing dataframes

In [5]:
PATH = get_path(2)
DATA_PATH = PATH + 'data/insumo/'

# Read data

In [6]:
df_train = pd.read_csv(
    DATA_PATH + 'train.csv', dtype={'nr_employed': str, 'Campana': str},
    na_values=['unknown']
    )

df_test = pd.read_csv(
    DATA_PATH + 'test.csv', dtype={'nr_employed': str, 'Campana':str},
    na_values=['unknown']
    )

# Data resume

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23099 entries, 0 to 23098
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  23099 non-null  int64
 1   Edad                23099 non-null  int64
 2   Tipo_Trabajo        22934 non-null  object
 3   Estado_Civil        23060 non-null  object
 4   Educacion           22141 non-null  object
 5   mora                18333 non-null  object
 6   Vivienda            22546 non-null  object
 7   Consumo             22546 non-null  object
 8   Contacto            23099 non-null  object
 9   Mes                 23099 non-null  object
 10  Dia                 23099 non-null  object
 11  Campana             23099 non-null  object
 12  Dias_Ultima_Camp    23099 non-null  int64
 13  No_Contactos        23099 non-null  int64
 14  Resultado_Anterior  23099 non-null  object
 15  emp_var_rate        23099 non-null  float64
 16  cons_price_idx      23099 non-null  float64
 17  cons_conf_idx       23099 non-null  float64
 18  euribor3m           23099 non-null  float64
 19  nr_employed         23099 non-null  object
 20  y                   23099 non-null  int64
dtypes: float64(4), int64(5), object(12)
memory usage: 3.7+ MB

In [8]:
df_train.describe()

,ID,Edad,Dias_Ultima_Camp,No_Contactos,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,y
count,23099.000000,23099.000000,23099.000000,23099.000000,23099.000000,23099.000000,23099.000000,23099.000000,23099.000000
mean,16420.136499,40.067665,962.976060,0.171003,0.095649,85576.471847,-40.485237,3190.939789,0.112126
std,9521.074915,10.449983,185.675409,0.494079,1.565650,26224.436234,4.629643,2088.703058,0.315528
min,1.000000,18.000000,0.000000,0.000000,-3.400000,93.200000,-50.800000,0.634000,0.000000
25%,8158.000000,32.000000,999.000000,0.000000,-1.800000,92893.000000,-42.700000,1281.000000,0.000000
50%,16375.000000,38.000000,999.000000,0.000000,1.100000,93876.000000,-41.800000,4856.000000,0.000000
75%,24644.500000,47.000000,999.000000,0.000000,1.400000,93994.000000,-36.400000,4961.000000,0.000000
max,32967.000000,95.000000,999.000000,6.000000,1.400000,94767.000000,-26.900000,5045.000000,1.000000

In [9]:
df_train.shape

(23099, 21)

In [10]:
df_train.isna().sum()

ID                       0
Edad                     0
Tipo_Trabajo           165
Estado_Civil            39
Educacion              958
mora                  4766
Vivienda               553
Consumo                553
Contacto                 0
Mes                      0
Dia                      0
Campana                  0
Dias_Ultima_Camp         0
No_Contactos             0
Resultado_Anterior       0
emp_var_rate             0
cons_price_idx           0
cons_conf_idx            0
euribor3m                0
nr_employed              0
y                        0
dtype: int64

In [11]:
df_test.isna().sum()

ID                       0
Edad                     0
Tipo_Trabajo            89
Estado_Civil            25
Educacion              418
mora                  2058
Vivienda               234
Consumo                234
Contacto                 0
Mes                      0
Dia                      0
Campana                  0
Dias_Ultima_Camp         0
No_Contactos             0
Resultado_Anterior       0
emp_var_rate             0
cons_price_idx           0
cons_conf_idx            0
euribor3m                0
nr_employed              0
dtype: int64

In [12]:
df_train.sample(n=5).head()

,ID,Edad,Tipo_Trabajo,Estado_Civil,Educacion,mora,Vivienda,Consumo,Contacto,Mes,Dia,Campana,Dias_Ultima_Camp,No_Contactos,Resultado_Anterior,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
5686,8028,41,empleado,casado,bachillerato incompleto,no,si,no,telefono fijo,jun,wed,6,999,0,sin contacto,1.4,94465.0,-41.8,4959.00,5228.1,0
4708,6595,36,emprendedor,casado,pregrado,no,si,no,telefono fijo,jun,tue,1,999,0,sin contacto,1.4,94465.0,-41.8,4864.00,5228.1,0
3748,5276,47,empleado,casado,preescolar,NaN,si,no,telefono fijo,may,wed,1,999,0,sin contacto,1.1,93994.0,-36.4,4857.00,5191,0
12014,17036,34,administrador negocio,casado,pregrado,no,no,no,telefono fijo,aug,mon,1,999,0,sin contacto,1.4,93444.0,-36.1,4963.00,5228.1,0
4174,5873,48,administrador negocio,divorced,bachillerato,no,si,no,telefono fijo,may,thu,2,999,0,sin contacto,1.1,93994.0,-36.4,4.86,5191,0

# Clear data

In [13]:
# Missing data
print(df_train.shape)
df_train.dropna(inplace=True)  # Process not necessary because there is no missing data
print(df_train.shape)

(23099, 21)
(17176, 21)

In [14]:
# Irrelevant columns
cols_cat = ['Tipo_Trabajo', 'Estado_Civil', 'Educacion', 'mora',
       'Vivienda', 'Consumo', 'Contacto', 'Mes', 'Dia', 'Campana',
       'Resultado_Anterior', 'nr_employed', 'y'
       ]

print('Delete irrelevant columns:')

for col in cols_cat:  # Counting the levels in the different categorical columns
  print(f'\t column {col}: {df_train[col].nunique()} sublevels')

Delete irrelevant columns:
	 column Tipo_Trabajo: 11 sublevels
	 column Estado_Civil: 5 sublevels
	 column Educacion: 7 sublevels
	 column mora: 2 sublevels
	 column Vivienda: 2 sublevels
	 column Consumo: 2 sublevels
	 column Contacto: 2 sublevels
	 column Mes: 10 sublevels
	 column Dia: 5 sublevels
	 column Campana: 38 sublevels
	 column Resultado_Anterior: 3 sublevels
	 column nr_employed: 11 sublevels
	 column y: 2 sublevels

In [15]:
# Duplicate rows
print(f'Set size before deleting repeated rows: {df_train.shape[0]}')
df_train.drop_duplicates(inplace=True)
print(f'Set size after deleting repeated rows: {df_train.shape[0]}')

Set size before deleting repeated rows: 17176
Set size after deleting repeated rows: 17176

In [16]:
fig = go.Figure()

fig.add_trace(go.Box(x=df_train['Edad'], name='Edad',
                marker_color = 'lightseagreen'))
fig.add_trace(go.Box(x=df_train['Dias_Ultima_Camp'], name='Dias_Ultima_Camp',
                marker_color = 'lightseagreen'))
fig.add_trace(go.Box(x=df_train['No_Contactos'], name='No_Contactos',
                marker_color = 'lightseagreen'))
fig.add_trace(go.Box(x=df_train['emp_var_rate'], name='emp_var_rate',
                marker_color = 'indianred'))
fig.add_trace(go.Box(x=df_train['cons_price_idx'], name='cons_price_idx',
                marker_color = 'indianred'))
fig.add_trace(go.Box(x=df_train['cons_conf_idx'], name='cons_conf_idx',
                marker_color = 'indianred'))
fig.add_trace(go.Box(x=df_train['euribor3m'], name='euribor3m',
                marker_color = 'indianred'))

fig.show()

In [17]:
# Represent in lowercase only if column is categorical
cols_cat = ['Tipo_Trabajo', 'Estado_Civil', 'Educacion', 'mora',
            'Vivienda', 'Consumo', 'Contacto', 'Mes', 'Dia', 'Campana',
            'Resultado_Anterior', 'nr_employed'
]

for column in df_train.columns:
    if column in cols_cat:
        df_train[column] = df_train[column].str.lower()

In [18]:
for column in df_train.columns:
    print(f"Repeated values in <{column}>:", df_train[column].isnull().sum())

Repeated values in <ID>: 0
Repeated values in <Edad>: 0
Repeated values in <Tipo_Trabajo>: 0
Repeated values in <Estado_Civil>: 0
Repeated values in <Educacion>: 0
Repeated values in <mora>: 0
Repeated values in <Vivienda>: 0
Repeated values in <Consumo>: 0
Repeated values in <Contacto>: 0
Repeated values in <Mes>: 0
Repeated values in <Dia>: 0
Repeated values in <Campana>: 0
Repeated values in <Dias_Ultima_Camp>: 0
Repeated values in <No_Contactos>: 0
Repeated values in <Resultado_Anterior>: 0
Repeated values in <emp_var_rate>: 0
Repeated values in <cons_price_idx>: 0
Repeated values in <cons_conf_idx>: 0
Repeated values in <euribor3m>: 0
Repeated values in <nr_employed>: 0
Repeated values in <y>: 0

In [19]:
# Manual label encoding
encode = {
    'si': 1, 'no': 0, 
    999: -1,
    'mon': 'lun', 'tue': 'mar', 'wed': 'mié', 'thu': 'jue', 'fri': 'vie',
    'jan': 'ene', 'feb': 'feb', 'mar': 'mar', 'apr': 'abr', 'may': 'may', 'jun': 'jun', 
    'jul': 'jul', 'aug': 'ago', 'sep': 'sep', 'oct': 'oct', 'nov': 'nov', 'dec': 'dic'
    }

df_train = df_train.replace(encode).infer_objects()
df_test = df_test.replace(encode).infer_objects()

In [20]:
# Define the values to be replaced in a dictionary
replace_dict = {
    'Estado_Civil': [('single', 'soltero'), ('divorced', 'divorciado')]
}

# Iterate over the columns and apply the function
for column, replacements in replace_dict.items():
    for old_value, new_value in replacements:
        df_train = replace_value(df_train, column, old_value, new_value)

## Conclusions

- Existen datos faltantes en variables (columnas) sociodemográficas; por esta razón, será necesario tratar el conjunto de datos durante el preprocesamiento.
- Las columnas *Tipo_trabajo*, *Educacion*, *mora*, *Vivienda*, *Consumo* cuentan con datos etiquetados como "desconocido".
- Debido a que cada variable (columna) tiene por lo menos dos subniveles de información no es posible descartar ninguna de ellas.
- No existen filas duplicadas.
- A nivel cualitativo no parecen existir datos anormales en las variables de tipo numérico del dataset.
- La columna *Estado_Civil* cuentan con errores de tipado en sus valores.
- La columna *Dias_Ultima_Camp* cuenta con un valor atípico (marca para distinguir a los clientes que no han podido ser contactados: sin contactar o fallidos).