In [11]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

from utilities import get_path, read_data_from_database

In [12]:
pd.options.display.max_columns = None  # Remove "dots" from display when printing dataframes

In [13]:
PATH = get_path(1)
DATABASE_FOLDER = PATH + 'data/preprocessing/clear_data.db'

In [14]:
df = read_data_from_database(DATABASE_FOLDER, 'train_table')

df.head()

,ID,Edad,Tipo_Trabajo,Estado_Civil,Educacion,mora,Vivienda,Consumo,Contacto,Mes,Dia,Campana,Dias_Ultima_Camp,No_Contactos,Resultado_Anterior,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,1,57,servicios,casado,bachillerato,NaN,0.0,0.0,telefono fijo,may,lun,1,-1,0,sin contacto,1.1,93994.0,-36.4,4857.0,5191,0
1,2,37,servicios,casado,bachillerato,0.0,1.0,0.0,telefono fijo,may,lun,1,-1,0,sin contacto,1.1,93994.0,-36.4,4857.0,5191,0
2,3,40,administrador negocio,casado,primaria,0.0,0.0,0.0,telefono fijo,may,lun,1,-1,0,sin contacto,1.1,93994.0,-36.4,4857.0,5191,0
3,4,56,servicios,casado,bachillerato,0.0,0.0,1.0,telefono fijo,may,lun,1,-1,0,sin contacto,1.1,93994.0,-36.4,4857.0,5191,0
4,7,25,servicios,soltero,bachillerato,0.0,1.0,0.0,telefono fijo,may,lun,1,-1,0,sin contacto,1.1,93994.0,-36.4,4857.0,5191,0

In [15]:
df.isnull().sum()

ID                       0
Edad                     0
Tipo_Trabajo           165
Estado_Civil            39
Educacion              958
mora                  4766
Vivienda               553
Consumo                553
Contacto                 0
Mes                      0
Dia                      0
Campana                  0
Dias_Ultima_Camp         0
No_Contactos             0
Resultado_Anterior       0
emp_var_rate             0
cons_price_idx           0
cons_conf_idx            0
euribor3m                0
nr_employed              0
y                        0
dtype: int64

In [16]:
# Simple imputation
df['Estado_Civil'].fillna(df['Estado_Civil'].mode()[0], inplace=True)
df['Tipo_Trabajo'].fillna(df['Tipo_Trabajo'].mode()[0], inplace=True)
df['Educacion'].fillna(df['Educacion'].mode()[0], inplace=True)

In [17]:
# KNN imputattion
cols_inputation = ['mora', 'Vivienda', 'Consumo']

for column in cols_inputation:
       number_neighbors = len(df[column].dropna().unique())
       imputer = KNNImputer(n_neighbors=number_neighbors, weights='uniform')

       print(f"Valores perdidos en {column}: {str(df[column].isnull().sum())}")

       imputer.fit(df[[column]])
       df[column] = imputer.transform(df[[column]]).ravel()

       print(f"Valores perdidos en {column}: {str(df[column].isnull().sum())}\n")

Valores perdidos en mora: 4766
Valores perdidos en mora: 0

Valores perdidos en Vivienda: 553
Valores perdidos en Vivienda: 0

Valores perdidos en Consumo: 553
Valores perdidos en Consumo: 0

In [18]:
df.isnull().sum()

ID                    0
Edad                  0
Tipo_Trabajo          0
Estado_Civil          0
Educacion             0
mora                  0
Vivienda              0
Consumo               0
Contacto              0
Mes                   0
Dia                   0
Campana               0
Dias_Ultima_Camp      0
No_Contactos          0
Resultado_Anterior    0
emp_var_rate          0
cons_price_idx        0
cons_conf_idx         0
euribor3m             0
nr_employed           0
y                     0
dtype: int64

# Datos faltantes

## Variables categóricas

In [19]:
df[['mora', 'Vivienda', 'Consumo', 'emp_var_rate', 'cons_price_idx', 
    'cons_conf_idx', 'euribor3m', 'Tipo_Trabajo']].sample(n=5).head(5)

,mora,Vivienda,Consumo,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,Tipo_Trabajo
15680,0.000000,1.0,0.0,-1.8,92843.0,-50.0,1629.0,tecnico
428,0.000109,0.0,0.0,1.1,93994.0,-36.4,4856.0,vendedor ambulante
20071,0.000000,1.0,0.0,-1.8,92893.0,-46.2,1244.0,vive de los arriendos
1333,0.000109,0.0,0.0,1.1,93994.0,-36.4,4856.0,tecnico
19025,0.000000,1.0,0.0,-1.8,92893.0,-46.2,1281.0,servicios

## Variables numéricas